package com.ku.dku.entity;
// Generated Apr 21, 2021 2:56:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsPublicRelation generated by hbm2java
 */
@Entity
@Table(name="ms_public_relation"
    //, catalog="dku"
)
public class MsPublicRelation  implements java.io.Serializable, BaseEntity {
	private static final long serialVersionUID = 1L;


    public static final String P_RECID = "recId";
    public static final String P_RELATIONNAME = "relationName";
    public static final String P_DESCRIPTION = "description";
    public static final String P_FILEID = "fileId";


    private Long recId;
    private String relationName;
    private String description;
    private Long fileId;

    public MsPublicRelation() {
    }


    public MsPublicRelation(String relationName, String description, Long fileId) {
        this.relationName = relationName;
        this.description = description;
        this.fileId = fileId;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    
    @Column(name="rec_id", unique=true, nullable=false)
    public Long getRecId() {
        return this.recId;
    }
    
    public void setRecId(Long recId) {
        this.recId = recId;
    }
    
    @Column(name="relation_name")
    public String getRelationName() {
        return this.relationName;
    }
    
    public void setRelationName(String relationName) {
        this.relationName = relationName;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="file_id")
    public Long getFileId() {
        return this.fileId;
    }
    
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }




}


