package com.ku.dku.entity;
// Generated Feb 11, 2021 11:10:26 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LkTerm generated by hbm2java
 */
@Entity
@Table(name="lk_term"
    //, catalog="dku"
)
public class LkTerm  implements java.io.Serializable, BaseEntity {
	private static final long serialVersionUID = 1L;


    public static final String P_RECID = "recId";
    public static final String P_TERMNAME = "termName";
    public static final String P_TERMID = "termId";


    private Long recId;
    private Long termName;
    private Long termId;

    public LkTerm() {
    }


    public LkTerm(Long termName, Long termId) {
        this.termName = termName;
        this.termId = termId;
    }
   
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    
    @Column(name="rec_id", unique=true, nullable=false)
    public Long getRecId() {
        return this.recId;
    }
    
    public void setRecId(Long recId) {
        this.recId = recId;
    }
    
    @Column(name="term_name")
    public Long getTermName() {
        return this.termName;
    }
    
    public void setTermName(Long termName) {
        this.termName = termName;
    }
    
    @Column(name="term_id")
    public Long getTermId() {
        return this.termId;
    }
    
    public void setTermId(Long termId) {
        this.termId = termId;
    }




}


