package com.ku.dku.entity;
// Generated Apr 21, 2021 2:56:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsFile generated by hbm2java
 */
@Entity
@Table(name="ms_file"
    //, catalog="dku"
)
public class MsFile  implements java.io.Serializable, BaseEntity {
	private static final long serialVersionUID = 1L;


    public static final String P_RECID = "recId";
    public static final String P_FILENAME = "fileName";
    public static final String P_FILETYPE = "fileType";
    public static final String P_FILEDATA = "fileData";
    public static final String P_TXSTUDENTID = "txStudentId";


    private Long recId;
    private String fileName;
    private String fileType;
    private byte[] fileData;
    private Long txStudentId;

    public MsFile() {
    }


    public MsFile(String fileName, String fileType, byte[] fileData, Long txStudentId) {
        this.fileName = fileName;
        this.fileType = fileType;
        this.fileData = fileData;
        this.txStudentId = txStudentId;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    
    @Column(name="rec_id", unique=true, nullable=false)
    public Long getRecId() {
        return this.recId;
    }
    
    public void setRecId(Long recId) {
        this.recId = recId;
    }
    
    @Column(name="file_name")
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="file_type")
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    
    @Column(name="file_data")
    public byte[] getFileData() {
        return this.fileData;
    }
    
    public void setFileData(byte[] fileData) {
        this.fileData = fileData;
    }
    
    @Column(name="tx_student_id")
    public Long getTxStudentId() {
        return this.txStudentId;
    }
    
    public void setTxStudentId(Long txStudentId) {
        this.txStudentId = txStudentId;
    }




}


