package com.ku.dku.entity;
// Generated Apr 16, 2021 2:10:49 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsRunningNumber generated by hbm2java
 */
@Entity
@Table(name="ms_running_number"
    //, catalog="dku"
)
public class MsRunningNumber  implements java.io.Serializable, BaseEntity {
	private static final long serialVersionUID = 1L;


    public static final String P_RECID = "recId";
    public static final String P_NUMBER = "number";
    public static final String P_DESCRIPTION = "description";


    private Long recId;
    private Integer number;
    private String description;

    public MsRunningNumber() {
    }


    public MsRunningNumber(Integer number, String description) {
        this.number = number;
        this.description = description;
    }
   
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    
    @Column(name="rec_id", unique=true, nullable=false)
    public Long getRecId() {
        return this.recId;
    }
    
    public void setRecId(Long recId) {
        this.recId = recId;
    }
    
    @Column(name="number", nullable=false)
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


