package com.ku.dku.entity;
// Generated Feb 11, 2021 11:10:26 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsYear generated by hbm2java
 */
@Entity
@Table(name="ms_year"
    //, catalog="dku"
)
public class MsYear  implements java.io.Serializable, BaseEntity {
	private static final long serialVersionUID = 1L;


    public static final String P_RECID = "recId";
    public static final String P_YEAR = "year";


    private Long recId;
    private Long year;

    public MsYear() {
    }


    public MsYear(Long year) {
        this.year = year;
    }
   
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    
    @Column(name="rec_id", unique=true, nullable=false)
    public Long getRecId() {
        return this.recId;
    }
    
    public void setRecId(Long recId) {
        this.recId = recId;
    }
    
    @Column(name="year")
    public Long getYear() {
        return this.year;
    }
    
    public void setYear(Long year) {
        this.year = year;
    }




}


