package com.ku.dku.entity;
// Generated Apr 20, 2021 7:08:40 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TxSetDateBail generated by hbm2java
 */
@Entity
@Table(name="tx_set_date_bail"
    //, catalog="dku"
)
public class TxSetDateBail  implements java.io.Serializable, BaseEntity {
	private static final long serialVersionUID = 1L;


    public static final String P_RECID = "recId";
    public static final String P_SETBAILSTART = "setBailStart";
    public static final String P_SETBAILDUE = "setBailDue";
    public static final String P_SETSTATUS = "setStatus";
    public static final String P_TERMID = "termId";
    public static final String P_SETPAYMENTSTART = "setPaymentStart";
    public static final String P_SETPAYMENTDUE = "setPaymentDue";
    public static final String P_YEAR = "year";


    private Long recId;
    private Date setBailStart;
    private Date setBailDue;
    private String setStatus;
    private Long termId;
    private Date setPaymentStart;
    private Date setPaymentDue;
    private Integer year;

    public TxSetDateBail() {
    }


    public TxSetDateBail(Date setBailStart, Date setBailDue, String setStatus, Long termId, Date setPaymentStart, Date setPaymentDue, Integer year) {
        this.setBailStart = setBailStart;
        this.setBailDue = setBailDue;
        this.setStatus = setStatus;
        this.termId = termId;
        this.setPaymentStart = setPaymentStart;
        this.setPaymentDue = setPaymentDue;
        this.year = year;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    
    @Column(name="rec_id", unique=true, nullable=false)
    public Long getRecId() {
        return this.recId;
    }
    
    public void setRecId(Long recId) {
        this.recId = recId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="set_bail_start", length=10)
    public Date getSetBailStart() {
        return this.setBailStart;
    }
    
    public void setSetBailStart(Date setBailStart) {
        this.setBailStart = setBailStart;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="set_bail_due", length=10)
    public Date getSetBailDue() {
        return this.setBailDue;
    }
    
    public void setSetBailDue(Date setBailDue) {
        this.setBailDue = setBailDue;
    }
    
    @Column(name="set_status")
    public String getSetStatus() {
        return this.setStatus;
    }
    
    public void setSetStatus(String setStatus) {
        this.setStatus = setStatus;
    }
    
    @Column(name="term_id")
    public Long getTermId() {
        return this.termId;
    }
    
    public void setTermId(Long termId) {
        this.termId = termId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="set_payment_start", length=10)
    public Date getSetPaymentStart() {
        return this.setPaymentStart;
    }
    
    public void setSetPaymentStart(Date setPaymentStart) {
        this.setPaymentStart = setPaymentStart;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="set_payment_due", length=10)
    public Date getSetPaymentDue() {
        return this.setPaymentDue;
    }
    
    public void setSetPaymentDue(Date setPaymentDue) {
        this.setPaymentDue = setPaymentDue;
    }
    
    @Column(name="year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }




}


